! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.3.1_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Function.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Function

  USE gckpp_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
!$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
!
! Fun - time derivatives of variables - Aggregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
!      Aout      - Array to return rxn rates for diagnostics (OPTIONAL)
!
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )

 USE gckpp_JacobianSP, only : DO_FUN

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)
!### KPP 2.3.0_gc, Bob Yantosca (11 Feb 2021)
!### Aout - Array for returning KPP reaction rates for diagnostics
  REAL(kind=dp), OPTIONAL :: Aout(NREACT)

! Computation of equation rates
  A(1) = RCT(1)*V(9)
  A(2) = RCT(2)*V(9)*V(10)
  A(3) = RCT(3)*V(6)*V(8)
  A(4) = RCT(4)*V(10)*V(11)
  A(5) = RCT(5)*V(12)
  A(6) = RCT(6)*V(11)*V(11)
  A(7) = RCT(7)*V(7)
  A(8) = RCT(8)*V(5)*V(8)
  A(9) = RCT(9)*V(7)*V(8)
  A(10) = RCT(10)*V(9)*V(11)
  A(11) = RCT(11)*V(8)*V(11)
  A(12) = RCT(12)*V(8)*V(12)


!### KPP 2.3.0_gc, Bob Yantosca (11 Feb 2021)
!### Use Aout to return reaction rates
  IF ( PRESENT( Aout ) ) Aout = A


! Aggregate function
IF (DO_FUN(1)) &
  Vdot(1) = A(3)
IF (DO_FUN(2)) &
  Vdot(2) = A(12)
IF (DO_FUN(3)) &
  Vdot(3) = A(9)+A(11)
IF (DO_FUN(4)) &
  Vdot(4) = A(1)+A(2)+A(6)+2*A(10)+A(11)
IF (DO_FUN(5)) &
  Vdot(5) = -A(8)
IF (DO_FUN(6)) &
  Vdot(6) = -A(3)+A(8)
IF (DO_FUN(7)) &
  Vdot(7) = A(6)-A(7)-A(9)
IF (DO_FUN(8)) &
  Vdot(8) = 2*A(1)-A(3)+A(4)+2*A(7)-A(8)-A(9)+A(10)-A(11)-A(12)
IF (DO_FUN(9)) &
  Vdot(9) = -A(1)-A(2)+A(5)-A(10)
IF (DO_FUN(10)) &
  Vdot(10) = -A(2)-A(4)+A(5)
IF (DO_FUN(11)) &
  Vdot(11) = A(3)-A(4)-2*A(6)+A(8)+A(9)-A(10)-A(11)
IF (DO_FUN(12)) &
  Vdot(12) = A(2)+A(4)-A(5)-A(12)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Function

