! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.3.1_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_JacobianSP.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(11) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  2,  3,  3,  4,  4,  4 /)

  INTEGER, PARAMETER, DIMENSION(11) :: LU_ICOL = (/ &
       1,  2,  4,  2,  3,  4,  3,  4,  2,  3,  4 /)

  INTEGER, PARAMETER, DIMENSION(5) :: LU_CROW = (/ &
       1,  4,  7,  9, 12 /)

  INTEGER, PARAMETER, DIMENSION(5) :: LU_DIAG = (/ &
       1,  4,  7, 11, 12 /)


END MODULE gckpp_JacobianSP

