! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.3.1_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_JacobianSP.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(9) :: LU_IROW = (/ &
       1,  2,  2,  2,  3,  3,  3,  4,  4 /)

  INTEGER, PARAMETER, DIMENSION(9) :: LU_ICOL = (/ &
       1,  2,  3,  4,  1,  3,  4,  3,  4 /)

  INTEGER, PARAMETER, DIMENSION(5) :: LU_CROW = (/ &
       1,  2,  5,  8, 10 /)

  INTEGER, PARAMETER, DIMENSION(5) :: LU_DIAG = (/ &
       1,  2,  6,  9, 10 /)

  LOGICAL, ALLOCATABLE :: DO_JVS(:)
  LOGICAL, ALLOCATABLE :: DO_SLV(:)
  LOGICAL, ALLOCATABLE :: DO_FUN(:)
  INTEGER, ALLOCATABLE :: cLU_IROW(:)  ! Compacted ROW indexes
  INTEGER, ALLOCATABLE :: cLU_ICOL(:)  ! Compacted COL indexes
  INTEGER, ALLOCATABLE :: cLU_CROW(:)  ! Compacted compressed row vector
  INTEGER, ALLOCATABLE :: cLU_DIAG(:)  ! Compacted DIAG indexes
  INTEGER, ALLOCATABLE :: JVS_MAP(:)   ! Map to JVS from compacted sparse data
  INTEGER, ALLOCATABLE :: SPC_MAP(:)   ! Map species (for Fun(), etc.)
  INTEGER :: rNVAR     ! Compacted number of variable species
  INTEGER :: cNONZERO  ! Compacted number of non-zero elements in cJVS

END MODULE gckpp_JacobianSP

