! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.3.1_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_JacobianSP.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(53) :: LU_IROW = (/ &
       1,  1,  1,  2,  2,  2,  3,  3,  3,  3,  4,  4, & ! index 1 - 12
       5,  5,  5,  6,  6,  6,  7,  7,  7,  7,  7,  8, & ! index 13 - 24
       8,  8,  8,  8,  8,  8,  8,  8,  9,  9,  9,  9, & ! index 25 - 36
       9,  9,  9,  9, 10, 10, 10, 10, 11, 11, 11, 11, & ! index 37 - 48
      12, 12, 12, 12, 12 /)

  INTEGER, PARAMETER, DIMENSION(53) :: LU_ICOL = (/ &
       1,  5,  8,  2,  8, 12,  3,  6,  8,  9,  4,  8, & ! index 1 - 12
       4,  5,  8,  6,  8,  9,  7,  8,  9, 10, 11,  4, & ! index 13 - 24
       5,  6,  7,  8,  9, 10, 11, 12,  4,  5,  6,  8, & ! index 25 - 36
       9, 10, 11, 12,  9, 10, 11, 12,  9, 10, 11, 12, & ! index 37 - 48
       8,  9, 10, 11, 12 /)

  INTEGER, PARAMETER, DIMENSION(13) :: LU_CROW = (/ &
       1,  4,  7, 11, 13, 16, 19, 24, 33, 41, 45, 49, & ! index 1 - 12
      54 /)

  INTEGER, PARAMETER, DIMENSION(13) :: LU_DIAG = (/ &
       1,  4,  7, 11, 14, 16, 19, 28, 37, 42, 47, 53, & ! index 1 - 12
      54 /)

  INTEGER, ALLOCATABLE :: DO_JVS(:)
  INTEGER, ALLOCATABLE :: DO_SLV(:)
  INTEGER, ALLOCATABLE :: DO_FUN(:)
  INTEGER, ALLOCATABLE :: cLU_IROW(:)  ! Compacted ROW indexes
  INTEGER, ALLOCATABLE :: cLU_ICOL(:)  ! Compacted COL indexes
  INTEGER, ALLOCATABLE :: cLU_CROW(:)  ! Compacted compressed row vector
  INTEGER, ALLOCATABLE :: cLU_DIAG(:)  ! Compacted DIAG indexes
  INTEGER, ALLOCATABLE :: JVS_MAP(:)   ! Map to JVS from compacted sparse data
  INTEGER, ALLOCATABLE :: SPC_MAP(:)   ! Map species (for Fun(), etc.)
  INTEGER :: rNVAR     ! Compacted number of variable species
  INTEGER :: cNONZERO  ! Compacted number of non-zero elements in cJVS

END MODULE gckpp_JacobianSP

