! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.3.1_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Jacobian.F90
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Jacobian

  USE gckpp_Parameters
  USE gckpp_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(20)

! B(1) = dA(1)/dV(7)
  B(1) = RCT(1)
! B(2) = dA(2)/dV(10)
  B(2) = RCT(2)*V(11)
! B(3) = dA(2)/dV(11)
  B(3) = RCT(2)*V(10)
! B(4) = dA(3)/dV(5)
  B(4) = RCT(3)*V(8)
! B(5) = dA(3)/dV(8)
  B(5) = RCT(3)*V(5)
! B(6) = dA(4)/dV(9)
  B(6) = RCT(4)*V(11)
! B(7) = dA(4)/dV(11)
  B(7) = RCT(4)*V(9)
! B(8) = dA(5)/dV(12)
  B(8) = RCT(5)
! B(9) = dA(6)/dV(9)
  B(9) = RCT(6)*2*V(9)
! B(10) = dA(7)/dV(6)
  B(10) = RCT(7)
! B(11) = dA(8)/dV(4)
  B(11) = RCT(8)*V(8)
! B(12) = dA(8)/dV(8)
  B(12) = RCT(8)*V(4)
! B(13) = dA(9)/dV(6)
  B(13) = RCT(9)*V(8)
! B(14) = dA(9)/dV(8)
  B(14) = RCT(9)*V(6)
! B(15) = dA(10)/dV(9)
  B(15) = RCT(10)*V(10)
! B(16) = dA(10)/dV(10)
  B(16) = RCT(10)*V(9)
! B(17) = dA(11)/dV(8)
  B(17) = RCT(11)*V(9)
! B(18) = dA(11)/dV(9)
  B(18) = RCT(11)*V(8)
! B(19) = dA(12)/dV(8)
  B(19) = RCT(12)*V(12)
! B(20) = dA(12)/dV(12)
  B(20) = RCT(12)*V(8)

! Construct the Jacobian terms from B's
IF (DO_JVS(1).eq.1) &
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
IF (DO_JVS(2).eq.1) &
! JVS(2) = Jac_FULL(1,5)
  JVS(2) = B(4)
IF (DO_JVS(3).eq.1) &
! JVS(3) = Jac_FULL(1,8)
  JVS(3) = B(5)
IF (DO_JVS(4).eq.1) &
! JVS(4) = Jac_FULL(2,2)
  JVS(4) = 0
IF (DO_JVS(5).eq.1) &
! JVS(5) = Jac_FULL(2,8)
  JVS(5) = B(19)
IF (DO_JVS(6).eq.1) &
! JVS(6) = Jac_FULL(2,12)
  JVS(6) = B(20)
IF (DO_JVS(7).eq.1) &
! JVS(7) = Jac_FULL(3,3)
  JVS(7) = 0
IF (DO_JVS(8).eq.1) &
! JVS(8) = Jac_FULL(3,6)
  JVS(8) = B(13)
IF (DO_JVS(9).eq.1) &
! JVS(9) = Jac_FULL(3,8)
  JVS(9) = B(14)+B(17)
IF (DO_JVS(10).eq.1) &
! JVS(10) = Jac_FULL(3,9)
  JVS(10) = B(18)
IF (DO_JVS(11).eq.1) &
! JVS(11) = Jac_FULL(4,4)
  JVS(11) = -B(11)
IF (DO_JVS(12).eq.1) &
! JVS(12) = Jac_FULL(4,8)
  JVS(12) = -B(12)
IF (DO_JVS(13).eq.1) &
! JVS(13) = Jac_FULL(5,4)
  JVS(13) = B(11)
IF (DO_JVS(14).eq.1) &
! JVS(14) = Jac_FULL(5,5)
  JVS(14) = -B(4)
IF (DO_JVS(15).eq.1) &
! JVS(15) = Jac_FULL(5,8)
  JVS(15) = -B(5)+B(12)
IF (DO_JVS(16).eq.1) &
! JVS(16) = Jac_FULL(6,6)
  JVS(16) = -B(10)-B(13)
IF (DO_JVS(17).eq.1) &
! JVS(17) = Jac_FULL(6,8)
  JVS(17) = -B(14)
IF (DO_JVS(18).eq.1) &
! JVS(18) = Jac_FULL(6,9)
  JVS(18) = B(9)
IF (DO_JVS(19).eq.1) &
! JVS(19) = Jac_FULL(7,7)
  JVS(19) = 0
IF (DO_JVS(20).eq.1) &
! JVS(20) = Jac_FULL(7,8)
  JVS(20) = B(17)
IF (DO_JVS(21).eq.1) &
! JVS(21) = Jac_FULL(7,9)
  JVS(21) = B(9)+2*B(15)+B(18)
IF (DO_JVS(22).eq.1) &
! JVS(22) = Jac_FULL(7,10)
  JVS(22) = B(2)+2*B(16)
IF (DO_JVS(23).eq.1) &
! JVS(23) = Jac_FULL(7,11)
  JVS(23) = B(3)
IF (DO_JVS(24).eq.1) &
! JVS(24) = Jac_FULL(8,4)
  JVS(24) = -B(11)
IF (DO_JVS(25).eq.1) &
! JVS(25) = Jac_FULL(8,5)
  JVS(25) = -B(4)
IF (DO_JVS(26).eq.1) &
! JVS(26) = Jac_FULL(8,6)
  JVS(26) = 2*B(10)-B(13)
IF (DO_JVS(27).eq.1) &
! JVS(27) = Jac_FULL(8,7)
  JVS(27) = 2*B(1)
IF (DO_JVS(28).eq.1) &
! JVS(28) = Jac_FULL(8,8)
  JVS(28) = -B(5)-B(12)-B(14)-B(17)-B(19)
IF (DO_JVS(29).eq.1) &
! JVS(29) = Jac_FULL(8,9)
  JVS(29) = B(6)+B(15)-B(18)
IF (DO_JVS(30).eq.1) &
! JVS(30) = Jac_FULL(8,10)
  JVS(30) = B(16)
IF (DO_JVS(31).eq.1) &
! JVS(31) = Jac_FULL(8,11)
  JVS(31) = B(7)
IF (DO_JVS(32).eq.1) &
! JVS(32) = Jac_FULL(8,12)
  JVS(32) = -B(20)
IF (DO_JVS(33).eq.1) &
! JVS(33) = Jac_FULL(9,4)
  JVS(33) = B(11)
IF (DO_JVS(34).eq.1) &
! JVS(34) = Jac_FULL(9,5)
  JVS(34) = B(4)
IF (DO_JVS(35).eq.1) &
! JVS(35) = Jac_FULL(9,6)
  JVS(35) = B(13)
IF (DO_JVS(36).eq.1) &
! JVS(36) = Jac_FULL(9,8)
  JVS(36) = B(5)+B(12)+B(14)-B(17)
IF (DO_JVS(37).eq.1) &
! JVS(37) = Jac_FULL(9,9)
  JVS(37) = -B(6)-2*B(9)-B(15)-B(18)
IF (DO_JVS(38).eq.1) &
! JVS(38) = Jac_FULL(9,10)
  JVS(38) = -B(16)
IF (DO_JVS(39).eq.1) &
! JVS(39) = Jac_FULL(9,11)
  JVS(39) = -B(7)
IF (DO_JVS(40).eq.1) &
! JVS(40) = Jac_FULL(9,12)
  JVS(40) = 0
IF (DO_JVS(41).eq.1) &
! JVS(41) = Jac_FULL(10,9)
  JVS(41) = -B(15)
IF (DO_JVS(42).eq.1) &
! JVS(42) = Jac_FULL(10,10)
  JVS(42) = -B(2)-B(16)
IF (DO_JVS(43).eq.1) &
! JVS(43) = Jac_FULL(10,11)
  JVS(43) = -B(3)
IF (DO_JVS(44).eq.1) &
! JVS(44) = Jac_FULL(10,12)
  JVS(44) = B(8)
IF (DO_JVS(45).eq.1) &
! JVS(45) = Jac_FULL(11,9)
  JVS(45) = -B(6)
IF (DO_JVS(46).eq.1) &
! JVS(46) = Jac_FULL(11,10)
  JVS(46) = -B(2)
IF (DO_JVS(47).eq.1) &
! JVS(47) = Jac_FULL(11,11)
  JVS(47) = -B(3)-B(7)
IF (DO_JVS(48).eq.1) &
! JVS(48) = Jac_FULL(11,12)
  JVS(48) = B(8)
IF (DO_JVS(49).eq.1) &
! JVS(49) = Jac_FULL(12,8)
  JVS(49) = -B(19)
IF (DO_JVS(50).eq.1) &
! JVS(50) = Jac_FULL(12,9)
  JVS(50) = B(6)
IF (DO_JVS(51).eq.1) &
! JVS(51) = Jac_FULL(12,10)
  JVS(51) = B(2)
IF (DO_JVS(52).eq.1) &
! JVS(52) = Jac_FULL(12,11)
  JVS(52) = B(3)+B(7)
IF (DO_JVS(53).eq.1) &
! JVS(53) = Jac_FULL(12,12)
  JVS(53) = -B(8)-B(20)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(5)+JVS(3)*UV(8)
  JUV(2) = JVS(4)*UV(2)+JVS(5)*UV(8)+JVS(6)*UV(12)
  JUV(3) = JVS(7)*UV(3)+JVS(8)*UV(6)+JVS(9)*UV(8)+JVS(10)*UV(9)
  JUV(4) = JVS(11)*UV(4)+JVS(12)*UV(8)
  JUV(5) = JVS(13)*UV(4)+JVS(14)*UV(5)+JVS(15)*UV(8)
  JUV(6) = JVS(16)*UV(6)+JVS(17)*UV(8)+JVS(18)*UV(9)
  JUV(7) = JVS(19)*UV(7)+JVS(20)*UV(8)+JVS(21)*UV(9)+JVS(22)*UV(10)+JVS(23)*UV(11)
  JUV(8) = JVS(24)*UV(4)+JVS(25)*UV(5)+JVS(26)*UV(6)+JVS(27)*UV(7)+JVS(28)*UV(8)+JVS(29)*UV(9)+JVS(30)*UV(10)+JVS(31)&
             &*UV(11)+JVS(32)*UV(12)
  JUV(9) = JVS(33)*UV(4)+JVS(34)*UV(5)+JVS(35)*UV(6)+JVS(36)*UV(8)+JVS(37)*UV(9)+JVS(38)*UV(10)+JVS(39)*UV(11)
  JUV(10) = JVS(41)*UV(9)+JVS(42)*UV(10)+JVS(43)*UV(11)+JVS(44)*UV(12)
  JUV(11) = JVS(45)*UV(9)+JVS(46)*UV(10)+JVS(47)*UV(11)+JVS(48)*UV(12)
  JUV(12) = JVS(49)*UV(8)+JVS(50)*UV(9)+JVS(51)*UV(10)+JVS(52)*UV(11)+JVS(53)*UV(12)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(4)*UV(2)
  JTUV(3) = JVS(7)*UV(3)
  JTUV(4) = JVS(11)*UV(4)+JVS(13)*UV(5)+JVS(24)*UV(8)+JVS(33)*UV(9)
  JTUV(5) = JVS(2)*UV(1)+JVS(14)*UV(5)+JVS(25)*UV(8)+JVS(34)*UV(9)
  JTUV(6) = JVS(8)*UV(3)+JVS(16)*UV(6)+JVS(26)*UV(8)+JVS(35)*UV(9)
  JTUV(7) = JVS(19)*UV(7)+JVS(27)*UV(8)
  JTUV(8) = JVS(3)*UV(1)+JVS(5)*UV(2)+JVS(9)*UV(3)+JVS(12)*UV(4)+JVS(15)*UV(5)+JVS(17)*UV(6)+JVS(20)*UV(7)+JVS(28)*UV(8)&
              &+JVS(36)*UV(9)+JVS(49)*UV(12)
  JTUV(9) = JVS(10)*UV(3)+JVS(18)*UV(6)+JVS(21)*UV(7)+JVS(29)*UV(8)+JVS(37)*UV(9)+JVS(41)*UV(10)+JVS(45)*UV(11)+JVS(50)&
              &*UV(12)
  JTUV(10) = JVS(22)*UV(7)+JVS(30)*UV(8)+JVS(38)*UV(9)+JVS(42)*UV(10)+JVS(46)*UV(11)+JVS(51)*UV(12)
  JTUV(11) = JVS(23)*UV(7)+JVS(31)*UV(8)+JVS(39)*UV(9)+JVS(43)*UV(10)+JVS(47)*UV(11)+JVS(52)*UV(12)
  JTUV(12) = JVS(6)*UV(2)+JVS(32)*UV(8)+JVS(44)*UV(10)+JVS(48)*UV(11)+JVS(53)*UV(12)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Jacobian

